"""add ingestion_runs table

Revision ID: 0949c3dd5b88
Revises: 9fd2d1b03bea
Create Date: 2026-09-10 22:09:27.893943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0949c3dd5b88'
down_revision: Union[str, Sequence[str], None] = '9fd2d1b03bea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    ingestion_runs is a brand new table - no backfill needed, nothing to
    migrate into it. client_records.ingestion_run_id stays nullable (like
    owner_id already is) rather than backfilled: there is no way to
    reconstruct, after the fact, which upload produced a record created
    before this column existed - the per-run summary this migration
    exists to make queryable was never persisted for those rows, only
    reported once in an HTTP response that's long gone. Old records
    simply read as "no known run" rather than being assigned a
    fabricated one.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('source_file', sa.String(), nullable=False),
    sa.Column('rows_total', sa.Integer(), nullable=False),
    sa.Column('rows_clean', sa.Integer(), nullable=False),
    sa.Column('rows_flagged', sa.Integer(), nullable=False),
    sa.Column('rows_dropped_duplicates', sa.Integer(), nullable=False),
    sa.Column('rows_skipped_existing', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_runs_owner_id'), 'ingestion_runs', ['owner_id'], unique=False)
    op.add_column('client_records', sa.Column('ingestion_run_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_client_records_ingestion_run_id'), 'client_records', ['ingestion_run_id'], unique=False)
    op.create_foreign_key(None, 'client_records', 'ingestion_runs', ['ingestion_run_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client_records', type_='foreignkey')
    op.drop_index(op.f('ix_client_records_ingestion_run_id'), table_name='client_records')
    op.drop_column('client_records', 'ingestion_run_id')
    op.drop_index(op.f('ix_ingestion_runs_owner_id'), table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    # ### end Alembic commands ###
