"""cascade delete webhook_deliveries with client_records

Revision ID: 9d13056a9c48
Revises: dbacb6e226e1
Create Date: 2026-09-10 13:54:52.164039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d13056a9c48'
down_revision: Union[str, Sequence[str], None] = 'dbacb6e226e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('webhook_deliveries_record_id_fkey'), 'webhook_deliveries', type_='foreignkey')
    op.create_foreign_key(None, 'webhook_deliveries', 'client_records', ['record_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'webhook_deliveries', type_='foreignkey')
    op.create_foreign_key(op.f('webhook_deliveries_record_id_fkey'), 'webhook_deliveries', 'client_records', ['record_id'], ['id'])
    # ### end Alembic commands ###
