"""add attempt_number to webhook_deliveries

Revision ID: 9fd2d1b03bea
Revises: 8bd3619c5dd2
Create Date: 2026-09-10 21:38:10.227641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fd2d1b03bea'
down_revision: Union[str, Sequence[str], None] = '8bd3619c5dd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Backfilled with server_default='1', not left nullable - every
    webhook_deliveries row that predates retries represents exactly one
    attempt (the only kind that existed before this migration), so 1 is
    the semantically correct value for all of them, not just a
    placeholder. Autogenerate's plain `nullable=False` with no default
    would fail outright against a production table that already has
    delivery rows (a real production/staging database is not empty here
    - this project's webhook flow has been live-tested against a real
    receiver, so webhook_deliveries already has rows by the time this
    migration would run there).
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'webhook_deliveries',
        sa.Column('attempt_number', sa.Integer(), nullable=False, server_default='1'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webhook_deliveries', 'attempt_number')
    # ### end Alembic commands ###
