"""add owner_id to client_records

Revision ID: dbacb6e226e1
Revises: ec536e50729c
Create Date: 2026-09-10 13:15:37.882359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbacb6e226e1'
down_revision: Union[str, Sequence[str], None] = 'ec536e50729c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_records', sa.Column('owner_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_client_records_owner_id'), 'client_records', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'client_records', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client_records', type_='foreignkey')
    op.drop_index(op.f('ix_client_records_owner_id'), table_name='client_records')
    op.drop_column('client_records', 'owner_id')
    # ### end Alembic commands ###
