"""cascade-delete owned rows when a user is deleted

Revision ID: e986a7123298
Revises: 0949c3dd5b88
Create Date: 2026-09-11 09:40:03.575285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e986a7123298'
down_revision: Union[str, Sequence[str], None] = '0949c3dd5b88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Backs DELETE /users/me (account self-erasure, main.py): without
    ondelete="cascade" on these three FKs, deleting a User would either
    fail outright (Postgres refuses to delete a row still referenced by
    another table's FK by default) or require the endpoint to manually
    walk and delete every ingestion_runs/client_records row first, in
    the right order, before the User row itself. Pure schema change -
    no data to migrate, no rows to backfill.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('client_records_ingestion_run_id_fkey'), 'client_records', type_='foreignkey')
    op.drop_constraint(op.f('client_records_owner_id_fkey'), 'client_records', type_='foreignkey')
    op.create_foreign_key(None, 'client_records', 'ingestion_runs', ['ingestion_run_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'client_records', 'users', ['owner_id'], ['id'], ondelete='cascade')
    op.drop_constraint(op.f('ingestion_runs_owner_id_fkey'), 'ingestion_runs', type_='foreignkey')
    op.create_foreign_key(None, 'ingestion_runs', 'users', ['owner_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ingestion_runs', type_='foreignkey')
    op.create_foreign_key(op.f('ingestion_runs_owner_id_fkey'), 'ingestion_runs', 'users', ['owner_id'], ['id'])
    op.drop_constraint(None, 'client_records', type_='foreignkey')
    op.drop_constraint(None, 'client_records', type_='foreignkey')
    op.create_foreign_key(op.f('client_records_owner_id_fkey'), 'client_records', 'users', ['owner_id'], ['id'])
    op.create_foreign_key(op.f('client_records_ingestion_run_id_fkey'), 'client_records', 'ingestion_runs', ['ingestion_run_id'], ['id'])
    # ### end Alembic commands ###
